services:
    # Flask is the Python web application that will run the AI chatbot.
    flask:
        build: .
        container_name: ai_flask
        volumes:
            - .:/flaskapp
        depends_on:
            - redis
        networks:
            - far_ai
#        healthcheck:
#          test: [ "CMD", "curl", "-f", "http://localhost:9001/api/v1/health" ]
#          interval: 30s
#          timeout: 10s
#          retries: 3
    # Redis is the in-memory data store that will be used to store chat histories.
    redis:
      image: redis
      container_name: ai_redis
      ports:
        - "6379:6379"
      networks:
        - far_ai
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 30s
        timeout: 10s
        retries: 3
    # Nginx is the reverse proxy that sits in front of the Gunicorn server.
    # (Gunicorn is included in the requirements.txt file and started in the Dockerfile)
    nginx:
      image: nginx
      container_name: ai_nginx
      ports:
        - "8000:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - flask
      networks:
        - far_ai
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
        interval: 30s
        timeout: 10s
        retries: 3

#    db:
#      image: mariadb:latest
#      container_name: ai_db
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#        MYSQL_DATABASE: ${DB_NAME}
#        MYSQL_USER: ${DB_USER}
#        MYSQL_PASSWORD: ${DB_PASS}
#      volumes:
#        - farchatdb:/var/lib/mysql
#      ports:
#        - "3307:3306"
#      networks:
#        - far_ai

#volumes:
#  farchatdb:

networks:
  far_ai: