apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flask
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: flask
    spec:
      containers:
        - image: flask
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9001/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: ai-flask
          ports:
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /flaskapp
              name: flask-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: flask-cm0
          name: flask-cm0
